import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft, ArrowRight, BookOpen, Brain, Check, ChevronDown, Crown, Droplets, FlaskConical, Gem, Leaf, Lightbulb, Map as MapIcon, Menu, RotateCcw, Search, Sparkles, Star, Store, Trophy, X, Zap} from 'lucide-react';
import './styles.css';
import './complete.css';
import './refinements.css';
import './modern.css';
import './task-clarity.css';
import './adventure.css';
import './intro.css';

const TASKS=[
 ['Zahlen-Quadrat 1','🔎','Logik + Beweisen'],['Gabriel, Valentin & Milo','🧠','Logik + Beweisen'],['Fang Varsenias Fehler 1','⚡','Rechnen'],['Multiplikations-Paare 1','⚡','Rechnen'],['Hannahs Quizproblem','🎯','Logik + Beweisen'],['Magisches Quadrat','✨','Logik + Beweisen'],['Wer lügt?','🧠','Logik + Beweisen'],['Die Zahlenwaage','⚖️','Rechnen + Logik'],['Karten nahe an 100','🃏','Rechnen + Logik'],['Die Perlen-Kiste','💎','Logik'],['Die Bank','🪑','Logik'],['Kalenderdetektivin','📅','Logik'],['Fang Varsenias Rechenweg','⚡🔎','Rechnen + Beweisen'],['Immer, manchmal oder nie?','💭','Logik + Beweisen'],['Vier Boxen','📦','Logik'],['Wer hat 8 Schokoladen?','🍫','Logik'],['Das Knopfproblem','🔘','Logik'],['Der Obstverkauf','🍎','Logik'],['Spielzeugautos','🚗','Logik'],['Lara gegen Varsenia','👑','Rechnen']
];
const FACTS=[[2,6],[3,4],[4,2],[2,8],[3,6],[4,5],[2,9],[3,3],[4,7],[2,5],[3,8],[4,4],[2,7],[3,5],[4,6],[2,3],[3,9],[4,8],[2,4],[3,7]];
const AREAS=[
 {name:'Detektivbüro',subtitle:'Spuren lesen und Muster prüfen',ingredient:'Sternenstaub',Icon:Search,Ingredient:Sparkles},
 {name:'Zauberlabor',subtitle:'Zahlen mischen und Regeln entdecken',ingredient:'Mondkristall',Icon:FlaskConical,Ingredient:Gem},
 {name:'Geheimarchiv',subtitle:'Hinweise ordnen und Fälle knacken',ingredient:'Geheimtinte',Icon:BookOpen,Ingredient:Droplets},
 {name:'Zaubermarkt',subtitle:'Schlaue Geschäfte und große Prüfungen',ingredient:'Goldblatt',Icon:Store,Ingredient:Leaf}
];
const CASE_HINTS=[
 ['Beginne mit einer Zeile, in der nur wenige Zahlen fehlen.','Prüfe für jedes leere Feld zusätzlich die Spalte.','Streiche alle Zahlen, die in Zeile oder Spalte schon vorkommen. Was übrig bleibt, muss ins Feld.'],
 ['Teste nacheinander, wer auf Platz 3 sein könnte.','Setze jede Person probeweise auf Platz 3 und prüfe ihre Aussage.','Nur eine Probe darf zu der Angabe passen, dass Platz 3 die Wahrheit sagt.'],
 ['Rechne nicht die ganze Aufgabe neu. Prüfe zuerst nur die beiden Faktoren.','Vergleiche die Aussage mit einer Kernaufgabe, die du sicher kennst.','Wenn du einen Fehler findest, ersetze nur das falsche Ergebnis.'],
 ['Suche zuerst ein Paar, das du sofort kennst.','Die Tauschaufgabe hat dasselbe Ergebnis.','Lege erst 6 × 8 und 8 × 8; dadurch bleiben für die anderen Karten weniger Möglichkeiten.'],
 ['Bei zehn richtigen Antworten wären es 30 Punkte.','Eine falsche statt einer richtigen Antwort verändert den Stand um 4 Punkte.','Frage dich, wie oft du 4 von 30 abziehen musst, um 22 zu erreichen.'],
 ['Jede Reihe muss 15 ergeben. Beginne oben.','Die 5 in der Mitte hilft bei Zeilen, Spalten und Diagonalen.','Berechne jedes leere Feld als 15 minus die beiden bekannten Zahlen.'],
 ['Nimm jede Person einmal als Besitzerin oder Besitzer des Schlüssels an.','Prüfe bei jeder Probe alle drei Aussagen.','Gesucht ist genau die Probe, bei der nur eine Aussage wahr bleibt.'],
 ['Beide Seiten der Waage wiegen gleich viel.','Addiere zuerst die beiden Gewichte auf der rechten Seite.','Ziehe danach das bekannte Gewicht auf der linken Seite ab.'],
 ['Die Zehnerstellen verändern die Summe besonders stark.','Verteile große und kleine Ziffern auf die beiden Zehnerstellen.','Prüfe mehrere erlaubte Summen und vergleiche jeweils den Abstand zu 100.'],
 ['Am Ende ist von jeder Farbe gleich viel da.','Teile zuerst die Gesamtzahl am Ende gleichmäßig auf drei Farben auf.','Arbeite dann jeden beschriebenen Schritt in umgekehrter Reihenfolge zurück.'],
 ['Hannah und Lara müssen einen Zweierblock bilden.','Milo darf weder neben Hannah noch neben Valentin sitzen.','Teste den Block Lara–Hannah in beiden Richtungen und setze die Jungen an die freien Außenplätze.'],
 ['Nach sieben Tagen ist wieder derselbe Wochentag.','Gehe vom 2. August zuerst genau eine Woche weiter.','Zähle vom 9. August noch bis zum 11. August und bestimme auch den Abstand.'],
 ['Prüfe, ob bei der Zerlegung immer derselbe zweite Faktor benutzt wurde.','7 × 8 kann als 5 × 8 plus 2 × 8 zerlegt werden.','Korrigiere zuerst nur den zweiten Teil und addiere anschließend beide Teilprodukte.'],
 ['„Immer“ braucht eine Regel, „nie“ einen Widerspruch und „manchmal“ zwei Gegenbeispiele.','Teste jede Aussage einmal mit kleinen Zahlen.','Für „manchmal“ brauchst du ein Beispiel, bei dem sie stimmt, und eines, bei dem sie nicht stimmt.'],
 ['Teile 80 zunächst gleich auf vier Boxen auf.','Der gleiche Endstand ist dein Ausgangspunkt für den Rückweg.','Mache Schritt 3, dann Schritt 2 und zuletzt Schritt 1 rückwärts.'],
 ['Markiere zuerst alle unmöglichen geraden und ungeraden Zahlen.','Hannah ist ungerade und hat mehr als Mia.','Wenn eine Zahl nur noch zu einem Mädchen passt, kannst du ihre ganze Zeile und Spalte abschließen.'],
 ['Berechne Gelb und Grün zuerst direkt aus den 24 orangenen Knöpfen.','Addiere danach Orange, Gelb und Grün. Das sind zwei Drittel.','Das blaue Drittel ist halb so groß wie die Summe der anderen drei Farben.'],
 ['Wenn es x Orangen sind, gibt es x + 2 Äpfel.','Berechne für eine Probe erst das Verkaufsgeld und dann den Bonus.','Teste Gesamtzahlen in der Nähe eines Vielfachen von 6 und prüfe, ob Verkaufsgeld plus Bonus genau 29 € ergibt.'],
 ['Berechne zuerst zwei Fünftel von 40.','Grün sind vier Autos mehr als Rot; Gelb ist bereits bekannt.','Addiere Rot und Grün und teile nach Farben getrennt durch vier Autos pro Box.'],
 ['Genauigkeit zählt vor Geschwindigkeit.','Nutze Tauschaufgaben und bekannte Kernaufgaben.','Überspringe eine schwere Aufgabe kurz und kehre später zu ihr zurück.']
];
const NOTES=[
 'Quelle: bulgarische Zahlenlogik. Prüft Ausschlussdenken und Begründungen. Die Sternzahl nicht vorsagen. Zögern kann auf unsystematisches Prüfen hinweisen.',
 'Quelle: Platzierungslogik. Prüft Widerspruchsdenken. Valentin ist Dritter, Milo Zweiter. Keine Person vorab ausschließen.',
 'Prüft schnellen Faktenabruf. Beobachte, ob 7 × 8 erinnert oder neu gerechnet wird. Lösungen nicht nach dem ersten Fehler nennen.',
 'Prüft Abruf in beide Richtungen. Richtige Paare: 56, 42, 48, 64. Bei Zögern nur zum bereits gelegten Paar zurückfragen.',
 'Quelle: Quizproblem. Antwort 8. Prüft Rückwärtsdenken und den Unterschied von 4 Punkten. Keine Gleichung vorsagen.',
 'Magisches 3×3-Quadrat mit Summe 15. Prüft systematisches Addieren und Diagonalen. Fehlende Zahlen: 1, 3, 7, 9.',
 'Genau eine Aussage stimmt. Hannah hat den Schlüssel. Prüft systematisches Testen aller Fälle.',
 'Zahlenwaage. Prüft Gleichheitsverständnis und Umkehraufgabe. Unbekanntes Gewicht: 8 kg.',
 'Ziffernkarten-Optimierung. Beste Summe: 71 + 34 = 105, Abstand zu 100 ist 5.',
 'Quelle: Perlenproblem. Anfang: 18, 30, 12. Prüft Rückwärtsdenken vom gleichen Endstand 24.',
 'Quelle: Sitzlogik. Gültige Reihenfolge z. B. Milo, Lara, Hannah, Valentin. Neben Valentin sitzt Hannah.',
 'Kalenderlogik. Der 11. August ist Donnerstag, der Abstand beträgt 9 Tage. Erst Wochenrhythmus nutzen lassen.',
 'Prüft Fehleranalyse statt nur Ergebnisprüfung. Fehler: Die restlichen Gruppen müssen 2 × 8 sein.',
 'Prüft Gegenbeispiele und Allgemeingültigkeit. Lara soll bei „manchmal“ ein Beispiel und ein Gegenbeispiel nennen.',
 'Quelle: Boxenproblem. Anfang: 26, 24, 2, 28. Vom Endstand 20 je Box rückwärts arbeiten.',
 'Quelle: Schokoladenlogik. Lara hat 8. Prüft systematische Elimination.',
 'Kleinere verifizierte Knopfzahlen. Orange 24, Gelb 32, Grün 18, Blau 37, gesamt 111.',
 'Verifizierte Euro-Variante. 8 Orangen zu 2 €, 10 Äpfel zu 1 €, 3 € Belohnung, Einnahme 29 €.',
 'Verifizierte Autovariante. 40 Autos: 16 rot, 20 grün, 4 gelb. In 4er-Boxen sind rot+grün neun Boxen, gelb eine.',
 'Prüft Einmaleins-Fluency. Erst Genauigkeit, bei Gleichstand Zeit vergleichen. Nicht währenddessen helfen.'
];
const load=()=>{try{return JSON.parse(localStorage.getItem('lara-v2')||'{}')}catch{return{}}};
const blankScores={rechnen:0,logik:0,beweisen:0};

function App(){
 const saved=load();
 const [task,setTask]=useState(saved.task||0),[completed,setCompleted]=useState(saved.completed||[]),[scores,setScores]=useState(saved.scores||blankScores);
 const completedRef=useRef(new Set(saved.completed||[]));
 const [answers,setAnswers]=useState(saved.answers||{}),[attempts,setAttempts]=useState({}),[feedback,setFeedback]=useState(''),[varsMode,setVarsMode]=useState(false),[drawer,setDrawer]=useState(false);
 const [mapOpen,setMapOpen]=useState(false),[hintLevels,setHintLevels]=useState(saved.hintLevels||{});
 const [introSeen,setIntroSeen]=useState(saved.introSeen===true),[showIntro,setShowIntro]=useState(saved.introSeen!==true);
 const done=completed.includes(task), key=`t${task}`;
 useEffect(()=>localStorage.setItem('lara-v2',JSON.stringify({task,completed,scores,answers,hintLevels,introSeen,lastBoss:answers.t19?.finished?{points:FACTS.filter(([a,b],i)=>Number(answers.t19.answers?.[i])===a*b).length,time:answers.t19.time}:saved.lastBoss||null})),[task,completed,scores,answers,hintLevels,introSeen]);
 useEffect(()=>{setFeedback('');setDrawer(false)},[task]);
 const setA=(v)=>setAnswers(a=>({...a,[key]:v}));
 const finish=(cats=['logik'],points=2)=>{if(completedRef.current.has(task))return;completedRef.current.add(task);const ingredient=AREAS[Math.floor(task/5)].ingredient;setCompleted(c=>[...c,task]);setScores(s=>{const n={...s};cats.forEach(x=>n[x]+=points);return n});setFeedback(`Fall gelöst! Du erhältst 1 × ${ingredient}.`)};
 const wrong=(hint='Schau dir die Bedingungen noch einmal nacheinander an.')=>{const n=(attempts[key]||0)+1;setAttempts(a=>({...a,[key]:n}));setFeedback(n===1?'Hmm … nochmal prüfen 🔎':hint)};
 const go=(n)=>{setTask(Math.max(0,Math.min(19,n)));setMapOpen(false)};
 const revealHint=()=>setHintLevels(levels=>({...levels,[key]:Math.min(3,(levels[key]||0)+1)}));
 const startAdventure=()=>{setIntroSeen(true);setShowIntro(false)};
 const introToMap=()=>{setIntroSeen(true);setShowIntro(false);setMapOpen(true)};
 const reset=()=>{if(confirm('Level 1 wirklich neu starten?\nLaras aktueller Fortschritt wird gelöscht.')){localStorage.removeItem('lara-v2');location.reload()}};
 if(showIntro)return <WelcomeScreen returning={introSeen} start={startAdventure} openMap={introToMap}/>;
 return <div className="app-shell">
   <Sidebar scores={scores} completed={completed} onReset={reset} onMap={()=>setMapOpen(true)} onIntro={()=>setShowIntro(true)}/>
   <main className="workspace">
    <header className="mobile-head"><button className="icon-btn" onClick={()=>setDrawer(true)} aria-label="Aufgaben öffnen"><Menu/></button><b>Laras Rätselbüro</b><button className="icon-btn" onClick={()=>setMapOpen(true)} aria-label="Fallkarte öffnen"><MapIcon/></button></header>
    <section className="task-head"><div><span className="task-kicker">{AREAS[Math.floor(task/5)].name} · Fall {task+1} von 20</span><h1>{TASKS[task][0]} <span>{TASKS[task][1]}</span></h1><p>{TASKS[task][2].replaceAll('Rechnen','Blitz').replaceAll('Logik','Spürsinn').replaceAll('Beweisen','Erklären')}</p></div><div className="head-actions"><button className="map-button" onClick={()=>setMapOpen(true)}><MapIcon/> Fallkarte</button><div className="head-mark">{TASKS[task][1]}</div></div></section>
    <section className="exercise">{task===19&&done?<Complete scores={scores} onReset={reset}/>:<Task task={task} value={answers[key]} setValue={setA} finish={finish} wrong={wrong} feedback={feedback} setFeedback={setFeedback}/>}{(task!==19||!done)&&<HintLadder hints={CASE_HINTS[task]} level={hintLevels[key]||0} reveal={revealHint}/>}<Feedback text={feedback} good={done}/><div className="task-nav"><button className="button secondary" disabled={task===0} onClick={()=>go(task-1)}><ArrowLeft/> Zurück</button><span>{done?'Fall gelöst · Zutat gesammelt':'Du kannst später zurückkommen'}</span>{task<19&&<button className="button primary" onClick={()=>go(task+1)}>Weiter <ArrowRight/></button>}</div></section>
    <section className="vars"><button onClick={()=>setVarsMode(v=>!v)}>Varsenia-Modus <ChevronDown className={varsMode?'open':''}/></button>{varsMode&&<p>{NOTES[task]}</p>}</section>
   </main>
   <TaskList task={task} completed={completed} go={go} drawer={drawer} close={()=>setDrawer(false)} onIntro={()=>{setDrawer(false);setShowIntro(true)}}/>
   {mapOpen&&<CaseMap task={task} completed={completed} go={go} close={()=>setMapOpen(false)}/>} 
 </div>
}

function WelcomeScreen({returning,start,openMap}){return <main className="welcome-screen"><button className="welcome-skip" onClick={start}>{returning?'Zurück zu den Fällen':'Einführung überspringen'} <ArrowRight/></button><section className="welcome-card"><div className="welcome-copy"><div className="welcome-brand"><Sparkles/><span>Laras Rätselbüro <b>& Zauberwirtschaft</b></span></div><span className="welcome-kicker">Ein geheimnisvoller Brief für Lara</span><h1>Hallo Lara, dein Rätselbüro ist geöffnet.</h1><p className="welcome-lead">In der magischen Stadt sind Zahlen verschwunden, Sitzplätze vertauscht und Marktstände völlig durcheinandergeraten. Zum Glück suchen alle genau eine schlaue Detektivin.</p><blockquote>„Löse die Fälle, sammle Zauberzutaten und bringe die Zauberwirtschaft wieder zum Leuchten.“<small>Varsenia</small></blockquote><div className="welcome-steps"><div><Search/><span><b>Fälle lösen</b><small>Spuren lesen und Lösungen erklären</small></span></div><div><Sparkles/><span><b>Zutaten sammeln</b><small>Jeder gelöste Fall bringt eine Belohnung</small></span></div><div><Lightbulb/><span><b>Hilfe holen</b><small>Drei Hinweise stehen bereit, wenn du sie brauchst</small></span></div></div><div className="welcome-actions"><button className="welcome-primary" onClick={start}>{returning?'Weiter rätseln':'Rätselbüro öffnen'} <ArrowRight/></button><button className="welcome-secondary" onClick={openMap}><MapIcon/> Erst die Fallkarte ansehen</button></div></div><div className="welcome-visual" aria-label="Lara vor ihrem magischen Rätselbüro"><div className="magic-orbit" aria-hidden="true"><span><Search/></span><span><Store/></span><span><Gem/></span></div><div className="welcome-avatar"><img src="/lara-avatar.png" width="420" height="420" alt="Lara, die Detektivin des Rätselbüros"/></div><div className="visual-note note-one"><Search/><span><small>Heute</small><b>20 neue Fälle</b></span></div><div className="visual-note note-two"><Sparkles/><span><small>Belohnung</small><b>Magische Zutaten</b></span></div></div></section></main>}

function Complete({scores,onReset}){const max=Math.max(...Object.values(scores)),tops=Object.entries(scores).filter(([,v])=>v===max).map(([k])=>k==='rechnen'?'Blitz ⚡':k==='logik'?'Spürsinn 🧠':'Erklären 🔎');return <div className="complete-screen"><Crown/><p>Level 1</p><h2>LARA, ALLE FÄLLE GELÖST ⭐</h2><div className="complete-scores"><div>⚡ <b>{scores.rechnen}</b><span>Blitz</span></div><div>🧠 <b>{scores.logik}</b><span>Spürsinn</span></div><div>🔎 <b>{scores.beweisen}</b><span>Erklären</span></div></div><h3>Deine Superkraft heute: {tops.join(' & ')}</h3><blockquote>„Ich will nicht nur deine Lösung sehen. Ich will entdecken, warum sie stimmen muss. 💜“<small>Varsenia</small></blockquote><div className="tomorrow"><b>Challenge für morgen</b><br/>Erfinde eine Aussage, die richtig klingt, aber einen versteckten Fehler hat. Morgen muss Varsenia ihn finden.</div><button className="button secondary" onClick={onReset}><RotateCcw/> Neu starten</button></div>}

function Sidebar({scores,completed,onReset,onMap,onIntro}){return <aside className="sidebar"><div className="brand"><Sparkles/> <span>Laras Rätselbüro<br/><b>& Zauberwirtschaft</b></span></div><div className="profile"><div className="avatar"><img src="/lara-avatar.png" width="160" height="160" alt="Illustration von Lara"/><i>💜</i></div><small>Für Lara</small><h2>Hallo Lara!</h2><p>Bereit für neue Fälle und Geheimnisse?</p></div><button className="map-launch" onClick={onMap}><MapIcon/><span><b>Fallkarte öffnen</b><small>Vier magische Orte</small></span><ArrowRight/></button><button className="intro-link" onClick={onIntro}><BookOpen/> Wie funktioniert das Spiel?</button><div className="progress-copy"><b>{completed.length} / 20 Fälle gelöst</b><div className="progress" aria-label={`${completed.length} von 20 Fällen gelöst`}><i style={{width:`${completed.length*5}%`}}/></div></div><div className="ingredient-mini" aria-label="Gesammelte Zauberzutaten">{AREAS.map(({ingredient,Ingredient},area)=><div key={ingredient} title={ingredient}><Ingredient/><b>{completed.filter(i=>Math.floor(i/5)===area).length}</b></div>)}</div><div className="score-list"><div><Zap/>Blitz <b>{scores.rechnen}</b></div><div><Brain/>Spürsinn <b>{scores.logik}</b></div><div><Search/>Erklären <b>{scores.beweisen}</b></div></div><div className="level"><Crown/><span><small>Aktuell</small><b>Level 1</b></span><strong><Star/> {scores.rechnen+scores.logik+scores.beweisen}</strong></div><button className="restart" onClick={onReset}><RotateCcw/> Neu starten</button></aside>}
function TaskList({task,completed,go,drawer,close,onIntro}){return <aside className={`task-list ${drawer?'shown':''}`}><div className="list-head"><div><small>Dein Weg</small><h2>Level 1</h2><p>Alle Fälle</p></div><button className="icon-btn close" onClick={close} aria-label="Aufgabenliste schließen"><X/></button></div><button className="tour-link" onClick={onIntro}><BookOpen/> Spielidee ansehen</button><div className="task-scroll">{TASKS.map((t,i)=>{const status=completed.includes(i)?'complete':i===task?'current':'open';return <button key={t[0]} className={`task-row ${status}`} onClick={()=>go(i)}><span>{status==='complete'?<Check/>:i+1}</span><div><b>{t[0]}</b><small>{t[1]} {status==='complete'?'Gelöst':status==='current'?'Gerade dran':'Offen'}</small></div></button>})}</div></aside>}
function HintLadder({hints,level,reveal}){return <section className="hint-ladder" aria-label="Freiwillige Hinweise"><div className="hint-top"><div><Lightbulb/><span><b>Denkhilfe</b><small>{level===0?'Nur wenn du sie brauchst':`${level} von 3 Hinweisen geöffnet`}</small></span></div><button onClick={reveal} disabled={level===3}>{level===0?'Ersten Hinweis zeigen':level<3?'Nächsten Hinweis zeigen':'Alle Hinweise geöffnet'}</button></div>{level>0&&<ol>{hints.slice(0,level).map((hint,i)=><li key={hint}><span>{i+1}</span><p>{hint}</p></li>)}</ol>}</section>}
function CaseMap({task,completed,go,close}){return <div className="map-scrim" role="dialog" aria-modal="true" aria-labelledby="map-title" onKeyDown={e=>e.key==='Escape'&&close()} onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="case-map"><header><div><span className="map-kicker">Laras magische Welt</span><h2 id="map-title">Die Fallkarte</h2><p>Wähle einen Ort und öffne direkt einen Fall.</p></div><button className="icon-btn" onClick={close} aria-label="Fallkarte schließen" autoFocus><X/></button></header><div className="map-grid">{AREAS.map(({name,subtitle,ingredient,Icon,Ingredient},area)=>{const start=area*5,count=completed.filter(i=>Math.floor(i/5)===area).length;return <article className={`map-area area-${area}`} key={name}><div className="area-head"><div className="area-icon"><Icon/></div><div><small>Ort {area+1}</small><h3>{name}</h3><p>{subtitle}</p></div></div><div className="case-nodes">{TASKS.slice(start,start+5).map((item,index)=>{const i=start+index,done=completed.includes(i);return <button className={`${i===task?'current':''} ${done?'done':''}`} onClick={()=>go(i)} aria-current={i===task?'page':undefined} key={item[0]}><span>{done?<Check/>:i+1}</span><b>{item[0]}</b><small>{done?'Gelöst':'Öffnen'}</small></button>})}</div><footer><Ingredient/><span><b>{count} × {ingredient}</b><small>{5-count} Zutaten noch zu finden</small></span></footer></article>})}</div></section></div>}
function Feedback({text,good}){return text&&<div className={`feedback ${good?'good':'try'}`} role="status" aria-live="polite">{good?<Check/>:<Search/>}<span>{text}</span></div>}
const Options=({items,value,onPick})=><div className="options">{items.map((x,i)=><button key={x} className={value===i?'selected':''} onClick={()=>onPick(i)}>{x}</button>)}</div>;
const NumberInputs=({labels,value=[],setValue})=><div className="number-inputs">{labels.map((x,i)=><label key={x}><span>{x}</span><input inputMode="numeric" value={value[i]||''} onChange={e=>{const n=[...value];n[i]=e.target.value;setValue(n)}}/></label>)}</div>;

function Latin({second=false,value={},setValue,finish,wrong,setFeedback}){const given=second?[1,0,3,0,0,4,0,2,2,0,4,0,0,3,0,1]:[1,0,4,0,0,3,0,2,0,1,0,0,3,0,0,0],solution=second?[1,2,3,4,3,4,1,2,2,1,4,3,4,3,2,1]:[1,2,4,3,4,3,1,2,2,1,3,4,3,4,2,1],vals=value.grid||{},correct=given.every((x,i)=>x||Number(vals[i])===solution[i]);const check=()=>{if(!correct)return wrong('Fast! Prüfe noch einmal die markierten Zeilen oder Spalten 🔎');if(second)finish(['logik']);else{setValue({...value,gridCorrect:true});setFeedback('Das ganze Quadrat stimmt! Jetzt beantworte noch die Sternfrage.')}};return <><p className="lead">In jeder Zeile und jeder Spalte müssen 1, 2, 3 und 4 genau einmal vorkommen.</p><div className="latin">{given.map((n,i)=>n?<div className="given" key={i}>{n}</div>:<select aria-label={`Feld ${i+1}`} className={!second&&i===14?'star-cell':''} key={i} value={vals[i]||''} onChange={e=>setValue({...value,grid:{...vals,[i]:e.target.value},gridCorrect:false})}><option value="">{!second&&i===14?'★':'?'}</option>{[1,2,3,4].map(v=><option key={v}>{v}</option>)}</select>)}</div><button className="button primary check" onClick={check}>Quadrat prüfen</button>{value.gridCorrect&&!second&&<div className="proof"><h3>Welche Zahl steht auf dem Stern?</h3><Options items={['1','2','3','4']} value={value.star} onPick={star=>setValue({...value,star})}/>{value.star===1&&<><h3>Warum muss dort die 2 stehen?</h3><Options items={['In der Sternzeile fehlen 1, 2 und 4. Die Spalte schließt 1 und 4 aus, also bleibt nur 2.','Weil Sterne immer für 2 stehen.','Weil 2 die kleinste gerade Zahl ist.']} value={value.proof} onPick={proof=>{setValue({...value,proof});proof===0?finish(['logik','beweisen']):wrong('Die Begründung muss Zeile und Spalte benutzen.')}}/></>}</div>}</>}

function Catch({hard=false,value={},setValue,finish,wrong}){const rows=hard?[['9 × 7 = 63',true],['8 × 6 = 42',false,48],['7 × 9 = 63',true],['8 × 7 = 54',false,56]]:[['7 × 8 = 54',false,56],['6 × 7 = 42',true],['8 × 8 = 64',true],['5 × 5 = 20',false,25]];const i=value.i||0,r=rows[i],choice=value.choice,correct=choice===r[1],needs=correct&&!r[1],fixed=Number(value.fix)===r[2];const next=()=>{if(!correct)return wrong(`Prüfe die Kernaufgabe ${r[0].split(' = ')[0]} noch einmal.`);if(needs&&!fixed)return wrong('Du hast den Fehler gefunden. Jetzt fehlt noch die richtige Zahl.');if(i===3)finish(['rechnen']);else setValue({i:i+1})};return <><div className="round">Aussage {i+1} von 4</div><div className="equation">{r[0]}</div><div className="decision"><button className={choice===true?'picked':''} onClick={()=>setValue({...value,choice:true})}>STIMMT</button><button className={choice===false?'picked':''} onClick={()=>setValue({...value,choice:false})}>FEHLER</button></div>{choice!==undefined&&correct&&<div className="inline-good">{r[1]?'Treffer!':'Okay, Detektivin. Dann korrigiere Varsenia 🔎'}</div>}{needs&&<input className="big-input" inputMode="numeric" value={value.fix||''} onChange={e=>setValue({...value,fix:e.target.value})} placeholder={`${r[0].split('=')[0]}= ?`}/>}<button className="button primary check" onClick={next}>{i===3?'Runde abschließen':'Nächste Aussage'}</button></>}

function Standard({task,value,setValue,finish,wrong}){const configs={
1:{text:<><p>Gabriel: „Ich bin Zweiter geworden.“</p><p>Valentin: „Gabriel ist Erster geworden.“</p><p>Milo: „Ich habe gewonnen!“</p><b>Die Person auf Platz 3 hat die Wahrheit gesagt.</b></>,q:'Wer könnte auf Platz 3 sein?',opts:['Gabriel','Valentin','Milo'],right:1,follow:'Auf welchem Platz ist Milo?',fopts:['1','2','3'],fright:1,cats:['logik','beweisen']},
4:{text:<><p>10 Fragen. Richtig: +3 Punkte. Falsch: -1 Punkt.</p><b>Hannah hat am Ende 22 Punkte.</b></>,q:'Wie viele Fragen hat sie richtig?',input:true,answer:'8',follow:'Welcher Beweis stimmt?',fopts:['8 ist nah an 22.','8 richtige = 24, 2 falsche = -2. Also 22.','10 minus 2 ist 8.'],fright:1,cats:['logik','beweisen']},
6:{text:<><p>Lara: „Hannah hat den Schlüssel.“</p><p>Hannah: „Milo hat den Schlüssel.“</p><p>Milo: „Ich habe den Schlüssel nicht.“</p><b>Genau eine Aussage ist wahr.</b></>,q:'Wer hat den Schlüssel?',opts:['Lara','Hannah','Milo'],right:1,follow:'Welche Prüfung beweist es?',fopts:['Bei Hannah sind nur Laras Worte wahr.','Hannah klingt ehrlich.','Milo nennt keinen Namen.'],fright:0,cats:['logik','beweisen']},
11:{text:<><p>Gabriel: „Valentin ist Erster.“</p><p>Valentin: „Milo ist Zweiter.“</p><p>Milo: „Gabriel ist Zweiter.“</p><b>Genau eine Aussage stimmt. Valentin ist nicht Erster.</b></>,q:'Wer ist Zweiter?',opts:['Gabriel','Valentin','Milo'],right:0,cats:['logik']},
12:{text:<p>Varsenia sagt: „7 × 8 = 54, weil 5 × 8 = 40 und 2 × 7 = 14. 40 + 14 = 54.“</p>,q:'Wo ist Varsenias Denkfehler?',opts:['5 × 8 ist falsch.','Für die restlichen 2 Gruppen müsste sie 2 × 8 rechnen.','40 + 14 ist falsch.','7 × 8 kann man nicht zerlegen.'],right:1,follow:'Ergänze: 2 × 8 und 7 × 8',inputs:['2 × 8','7 × 8'],answers:['16','56'],cats:['rechnen','beweisen']},
16:{text:<><div className="story-intro"><span className="story-icon" aria-hidden="true">🧵</span><div><b>Knöpfe für vier Zaubermäntel</b><p>In Laras Werkstatt liegen orange, gelbe, grüne und blaue Knöpfe. Lara kennt noch nicht von jeder Farbe die Anzahl.</p></div></div><div className="color-facts"><p><b>🟠 Orange</b><strong>24 Knöpfe</strong></p><p><b>🟡 Gelb</b><span>8 mehr als Orange</span></p><p><b>🟢 Grün</b><span>6 weniger als Orange</span></p><p><b>🔵 Blau</b><span>ein Drittel von allen Knöpfen</span></p></div><div className="solve-path"><b>So kannst du vorgehen</b><ol><li>Berechne zuerst Gelb und Grün mit den 24 orangenen Knöpfen.</li><li>Addiere Orange, Gelb und Grün.</li><li>Diese drei Farben sind zwei Drittel aller Knöpfe. Blau ist das fehlende Drittel.</li></ol></div></>,q:'Wie viele Knöpfe liegen von jeder fehlenden Farbe in der Werkstatt?',inputs:['🟡 Gelbe Knöpfe','🟢 Grüne Knöpfe','🔵 Blaue Knöpfe'],answers:['32','18','37'],hint:'Berechne zuerst Gelb und Grün. Addiere dann die drei nicht-blauen Farben. Blau ist halb so viel wie diese Summe.',cats:['logik']},
17:{text:<><div className="story-intro"><span className="story-icon" aria-hidden="true">🍎</span><div><b>Verkauf am Zaubermarkt</b><p>Lara verkauft Äpfel und Orangen. Am Ende zählt sie das Geld aus dem Verkauf und den Bonus zusammen.</p></div></div><div className="price-cards"><p><span>Apfel</span><strong>1 €</strong><small>pro Stück</small></p><p><span>Orange</span><strong>2 €</strong><small>pro Stück</small></p><p><span>Markt-Bonus</span><strong>+ 1 €</strong><small>für je 6 verkaufte Früchte</small></p></div><div className="market-clues"><p><span>1</span>Lara verkauft genau <b>2 Äpfel mehr</b> als Orangen.</p><p><span>2</span>Verkaufsgeld und Bonus ergeben zusammen <b>29 €</b>.</p></div><p className="helper"><b>Denkhilfe:</b> Die Zahl aller verkauften Früchte verrät dir den Bonus. Für 6 Früchte gibt es 1 €, für 12 Früchte 2 €, für 18 Früchte 3 € und so weiter.</p></>,q:'Wie viele Äpfel und wie viele Orangen hat Lara verkauft?',inputs:['🍎 Äpfel','🍊 Orangen'],answers:['10','8'],hint:'Wenn du eine Zahl für die Orangen testest, müssen es zwei Äpfel mehr sein. Rechne erst das Verkaufsgeld und addiere danach den Bonus.',cats:['logik']},
18:{text:<><p>Es gibt <b>40 Spielzeugautos</b>.</p><p><b>2/5</b> davon sind rot. Es gibt <b>4 grüne Autos mehr</b> als rote. Die restlichen <b>4 Autos sind gelb</b>.</p><p>Immer <b>4 gleichfarbige Autos</b> kommen in eine Box.</p></>,q:'Wie viele Boxen braucht man für Rot und Grün zusammen? Wie viele für Gelb?',inputs:['Rote + grüne Boxen','Gelbe Boxen'],answers:['9','1'],cats:['logik']}
};const c=configs[task],v=value||{};const firstOk=c.input?String(v.first)===c.answer:c.inputs?c.answers.every((x,i)=>String(v.nums?.[i])===x):v.first===c.right;const submit=()=>{if(!firstOk)return wrong(c.hint||(task===4?'Wenn alle richtig wären, gäbe es 30 Punkte. Eine falsche statt einer richtigen Antwort verändert 4 Punkte.':'Teste die Angaben einzeln und prüfe, ob alle gleichzeitig stimmen.'));if(c.follow&&!c.inputs){if(v.follow!==c.fright)return wrong('Die Begründung muss aus allen Angaben folgen.')}finish(c.cats)};return <><div className="problem">{c.text}</div><h3>{c.q}</h3>{c.input?<input className="big-input" inputMode="numeric" value={v.first||''} onChange={e=>setValue({...v,first:e.target.value})}/>:c.inputs?<NumberInputs labels={c.inputs} value={v.nums} setValue={nums=>setValue({...v,nums})}/>:<Options items={c.opts} value={v.first} onPick={first=>setValue({...v,first})}/>} {firstOk&&c.follow&&!c.inputs&&<div className="proof"><h3>{c.follow}</h3><Options items={c.fopts} value={v.follow} onPick={follow=>setValue({...v,follow})}/></div>}<button className="button primary check" onClick={submit}>Prüfen</button></>}

function Task({task,...p}){if(task===0)return <Latin {...p}/>;if(task===5)return <MagicSquare {...p}/>;if(task===2)return <Catch {...p}/>;if([1,4,6,12,16,17,18].includes(task))return <Standard task={task} {...p}/>;if(task===3)return <Pairs {...p}/>;if(task===7)return <Balance {...p}/>;if(task===8)return <CardChallenge {...p}/>;if(task===9)return <NumericProblem {...p} labels={['Gelb','Orange','Schwarz']} answer={['18','30','12']} text="In der Kiste sind zuerst 60 Perlen. Danach kommen 6 gelbe dazu, 6 orange werden weggenommen und die schwarzen werden verdoppelt. Am Ende sind es von jeder Farbe gleich viele. Rechne jeden Schritt rückwärts."/>;if(task===10)return <Seats {...p}/>;if(task===11)return <CalendarTask {...p}/>;if(task===13)return <Statements {...p}/>;if(task===14)return <NumericProblem {...p} labels={['Box A','Box B','Box C','Box D']} answer={['26','24','2','28']} text="In vier Boxen liegen zusammen 80 Sticker. Am Ende liegt in jeder Box gleich viel. Schritt 1: 6 Sticker gehen von A nach B. Schritt 2: Danach geht ein Drittel aus B nach C. Schritt 3: 8 Sticker gehen von D nach C. Welche Mengen lagen am Anfang in den Boxen? Finde zuerst selbst heraus, wie viele am Ende in jeder Box liegen, und arbeite dann rückwärts."/>;if(task===15)return <Chocolate {...p}/>;return <Boss {...p}/>}
function NumericProblem({value={},setValue,finish,wrong,labels,answer,text}){const ok=answer.every((x,i)=>String(value.nums?.[i])===x);return <><div className="problem"><p>{text}</p></div><h3>Wie viele waren es am Anfang?</h3><NumberInputs labels={labels} value={value.nums} setValue={nums=>setValue({...value,nums})}/><button className="button primary check" onClick={()=>ok?finish(['logik']):wrong('Beginne beim gleichen Endstand und rechne die Schritte rückwärts.')}>Prüfen</button></>}
function Pairs({reverse=false,value={},setValue,finish,wrong}){const left=reverse?['42','48','56','64']:['7 × 8','6 × 7','6 × 8','8 × 8'],right=reverse?['6 × 8','8 × 8','6 × 7','7 × 8']:['42','64','48','56'],map=reverse?{'42':'6 × 7','48':'6 × 8','56':'7 × 8','64':'8 × 8'}:{'7 × 8':'56','6 × 7':'42','6 × 8':'48','8 × 8':'64'},pairs=value.pairs||{},sel=value.sel;const pick=r=>{if(!sel)return;if(map[sel]===r)setValue({...value,pairs:{...pairs,[sel]:r},sel:null});else wrong()};const all=Object.keys(pairs).length===4;return <><p className="lead">Verbinde jede Karte mit ihrem passenden Partner.</p><div className="pair-grid"><div>{left.map(x=><button disabled={pairs[x]} className={sel===x?'selected':''} onClick={()=>setValue({...value,sel:x})} key={x}>{x}</button>)}</div><div>{right.map(x=><button disabled={Object.values(pairs).includes(x)} onClick={()=>pick(x)} key={x}>{x}</button>)}</div></div>{all&&reverse&&<label className="extra">Finde eine zweite Aufgabe mit Ergebnis 48.<input value={value.extra||''} onChange={e=>setValue({...value,extra:e.target.value})} placeholder="z. B. 8 × 6"/></label>}<button className="button primary check" onClick={()=>all&&(!reverse||/^(8\s*[×x*]\s*6|6\s*[×x*]\s*8)$/.test(value.extra||''))?finish(['rechnen']):wrong('Nutze die Tauschaufgabe: Die Faktoren dürfen ihre Plätze wechseln.')}>Prüfen</button></>}
function Seats({value={},setValue,finish,wrong}){const people=[['Lara','👧🏼'],['Hannah','👧🏻'],['Milo','👦🏻'],['Valentin','👦🏼']],seats=value.seats||[],selected=value.selected,valid=seats.join(',')==='Milo,Lara,Hannah,Valentin'||seats.join(',')==='Valentin,Hannah,Lara,Milo';const place=(name,i)=>{const next=seats.map(x=>x===name?'':x);next[i]=name;setValue({...value,seats:next,selected:''})};return <><div className="problem"><p><b>Setze zwei Mädchen und zwei Jungen auf die Bank.</b></p><p>Hannah sitzt direkt neben Lara. Hannah sitzt nicht neben Milo. Milo sitzt nicht neben Valentin.</p><p>Ziehe die Kinder auf einen Platz oder wähle ein Kind aus und tippe danach auf einen Sitz.</p></div><div className="people-cards">{people.map(([name,face])=><button draggable onDragStart={e=>e.dataTransfer.setData('text/plain',name)} className={selected===name?'selected':''} onClick={()=>setValue({...value,selected:name})} key={name}><span>{face}</span><b>{name}</b><small>{name==='Lara'||name==='Hannah'?'Mädchen':'Junge'}</small></button>)}</div><div className="seats">{[0,1,2,3].map(i=><button onDragOver={e=>e.preventDefault()} onDrop={e=>place(e.dataTransfer.getData('text/plain'),i)} onClick={()=>selected&&place(selected,i)} key={i}><small>Platz {i+1}</small><strong>{seats[i]||'Hier absetzen'}</strong></button>)}</div><button className="button secondary" onClick={()=>setValue({})}>Leeren</button><button className="button primary check" onClick={()=>valid?finish(['logik']):wrong('Prüfe zuerst, wer ganz außen sitzen kann. Hannah muss direkt neben Lara sitzen.')}>Anordnung prüfen</button></>}
function Patterns({value={},setValue,finish,wrong}){const ok=value.a==='16'&&value.b==='30'&&value.c==='42'&&value.rule===1;return <><div className="patterns">{[['4, 7, 10, 13,','a'],['2, 6, 12, 20,','b'],['3, 6, 12, 21, 33,','c']].map(([s,k])=><label key={k}>{s}<input inputMode="numeric" value={value[k]||''} onChange={e=>setValue({...value,[k]:e.target.value})}/></label>)}</div><h3>Welche Regel gehört zum zweiten Muster?</h3><Options value={value.rule} onPick={rule=>setValue({...value,rule})} items={['Immer +4','+4, +6, +8, +10','Immer verdoppeln']}/><button className="button primary check" onClick={()=>ok?finish(['logik','beweisen']):wrong('Schau nicht nur auf die Zahlen, sondern auf die Abstände dazwischen.')}>Prüfen</button></>}
function Chocolate({value={},setValue,finish,wrong}){const names=['Hannah','Lara','Mia','Emma'],nums=[5,6,7,8],cells=value.cells||{};const cycle=(k)=>setValue({...value,cells:{...cells,[k]:cells[k]==='no'?'yes':cells[k]==='yes'?'':'no'}});return <><div className="problem"><p>Vier Mädchen haben unterschiedlich viele Schokoladen: <b>5, 6, 7 und 8</b>. Jede Zahl gehört genau zu einem Mädchen.</p><ul><li>Emma hat nicht 8.</li><li>Mia hat eine gerade Anzahl.</li><li>Hannah hat eine ungerade Anzahl.</li><li>Hannah hat mehr als Mia.</li></ul><p><b>So benutzt du die Tabelle:</b> Einmal tippen bedeutet unmöglich ×, zweimal tippen bedeutet bestätigt ✓.</p></div><div className="elim"><i></i>{nums.map(n=><b key={n}>{n}</b>)}{names.flatMap(n=>[<strong key={n}>{n}</strong>,...nums.map(x=><button aria-label={`${n} hat ${x}`} key={n+x} className={cells[n+x]||''} onClick={()=>cycle(n+x)}>{cells[n+x]==='no'?'×':cells[n+x]==='yes'?'✓':'·'}</button>)])}</div><h3>Wer hat 8 Schokoladen?</h3><Options items={names} value={value.pick} onPick={pick=>setValue({...value,pick})}/><button className="button primary check" onClick={()=>value.pick===1?finish(['logik']):wrong('Beginne mit Hannah: Sie hat eine ungerade Zahl und mehr als Mia.')}>Prüfen</button></>}
function MagicSquare({value={},setValue,finish,wrong}){const solution={1:'1',3:'3',5:'7',7:'9'},cells=value.cells||{},ok=Object.entries(solution).every(([i,n])=>cells[i]===n);return <><div className="problem"><p>Trage die fehlenden Zahlen von 1 bis 9 ein. Jede Zahl wird genau einmal benutzt.</p><p><b>Magische Regel:</b> Jede Zeile, jede Spalte und beide Diagonalen ergeben 15.</p></div><div className="magic-grid">{[8,'',6,'',5,'',4,'',2].map((n,i)=>n?<div key={i}>{n}</div>:<input key={i} aria-label={`Magisches Feld ${i+1}`} inputMode="numeric" value={cells[i]||''} onChange={e=>setValue({...value,cells:{...cells,[i]:e.target.value}})}/>)}</div><h3>Warum heißt das Quadrat „magisch“?</h3><Options items={['Nur die waagerechten Reihen ergeben 15.','Zeilen, Spalten und Diagonalen ergeben dieselbe Summe.','Weil die 5 in der Mitte steht.']} value={value.proof} onPick={proof=>setValue({...value,proof})}/><button className="button primary check" onClick={()=>ok&&value.proof===1?finish(['logik','beweisen']):wrong('Prüfe jede Zeile, Spalte und auch beide Diagonalen mit der Summe 15.')}>Prüfen</button></>}
function Balance({value={},setValue,finish,wrong}){const ok=value.weight==='8'&&value.proof===1;return <><div className="problem"><p>Die Waage ist genau im Gleichgewicht. Auf beiden Seiten liegt also dasselbe Gewicht.</p></div><div className="balance"><div><span>3 kg</span><span className="mystery">? kg</span></div><b>⚖️</b><div><span>5 kg</span><span>6 kg</span></div></div><label className="extra">Wie schwer ist das unbekannte Gewicht?<input inputMode="numeric" value={value.weight||''} onChange={e=>setValue({...value,weight:e.target.value})} placeholder="? kg"/></label><h3>Welche Rechnung beweist deine Lösung?</h3><Options items={['11 - 3 = 7','5 + 6 = 11 und 11 - 3 = 8','5 + 3 = 8'] } value={value.proof} onPick={proof=>setValue({...value,proof})}/><button className="button primary check" onClick={()=>ok?finish(['rechnen','logik']):wrong('Berechne zuerst das Gesamtgewicht auf der rechten Seite.')}>Waage prüfen</button></>}
function CardChallenge({value={},setValue,finish,wrong}){const clean=(value.expression||'').replace(/\s/g,''),valid=['71+34','34+71'].includes(clean),ok=valid&&value.result==='105'&&value.proof===0;return <><div className="problem"><p>Nutze jede Ziffernkarte genau einmal und bilde zwei zweistellige Zahlen.</p><p>Addiere sie. Dein Ergebnis soll möglichst nahe an 100 liegen.</p></div><div className="digit-cards">{['1','3','4','7'].map(n=><span key={n}>{n}</span>)}</div><div className="card-answer"><input value={value.expression||''} onChange={e=>setValue({...value,expression:e.target.value})} placeholder="z. B. 71 + 34"/><span>=</span><input inputMode="numeric" value={value.result||''} onChange={e=>setValue({...value,result:e.target.value})} placeholder="Ergebnis"/></div><h3>Wie weit liegt dein Ergebnis von 100 entfernt?</h3><Options items={['5','8','10']} value={value.proof} onPick={proof=>setValue({...value,proof})}/><button className="button primary check" onClick={()=>ok?finish(['rechnen','logik']):wrong('Die größte Ziffer muss bei den Zehnern gut ausgeglichen werden. Probiere 71 und 34.')}>Karten prüfen</button></>}
function CalendarTask({value={},setValue,finish,wrong}){const ok=value.day===3&&value.distance==='9';return <><div className="problem"><p>Am <b>Dienstag, 2. August</b>, beginnt Laras Ferienkurs.</p><p>Das Abschlussfest ist am <b>11. August</b>.</p></div><div className="calendar-strip">{[2,3,4,5,6,7,8,9,10,11].map((n,i)=><div className={n===2||n===11?'marked':''} key={n}><small>{['Di','Mi','Do','Fr','Sa','So','Mo'][i%7]}</small><b>{n}</b></div>)}</div><h3>Auf welchen Wochentag fällt der 11. August?</h3><Options items={['Montag','Dienstag','Mittwoch','Donnerstag','Freitag']} value={value.day} onPick={day=>setValue({...value,day})}/><label className="extra">Wie viele Tage liegen zwischen dem 2. und dem 11. August?<input inputMode="numeric" value={value.distance||''} onChange={e=>setValue({...value,distance:e.target.value})}/></label><button className="button primary check" onClick={()=>ok?finish(['logik']):wrong('Nach sieben Tagen ist wieder Dienstag. Zähle von dort noch weiter.')}>Kalender prüfen</button></>}
function Statements({value={},setValue,finish,wrong}){const answers=['immer','nie','manchmal'],picks=value.picks||{};const ok=answers.every((a,i)=>picks[i]===a);return <><div className="problem"><p>Entscheide für jede Behauptung: Gilt sie immer, manchmal oder nie?</p></div><div className="statements">{['Die Summe aus zwei ungeraden Zahlen ist gerade.','Eine Zahl ist gleichzeitig ungerade und ohne Rest durch 2 teilbar.','Die Summe aus zwei natürlichen Zahlen ist größer als 20.'].map((s,i)=><label key={s}><span>{s}</span><select value={picks[i]||''} onChange={e=>setValue({...value,picks:{...picks,[i]:e.target.value}})}><option value="">Auswählen</option><option value="immer">Immer</option><option value="manchmal">Manchmal</option><option value="nie">Nie</option></select></label>)}</div><h3>Welches Beispiel beweist „manchmal“?</h3><Options items={['3 + 4 = 7 und 12 + 11 = 23','11 + 11 = 22','2 + 2 = 4']} value={value.proof} onPick={proof=>setValue({...value,proof})}/><button className="button primary check" onClick={()=>ok&&value.proof===0?finish(['logik','beweisen']):wrong('Für „manchmal“ brauchst du ein Beispiel, bei dem es stimmt, und eines, bei dem es nicht stimmt.')}>Aussagen prüfen</button></>}
function Boss({value={},setValue,finish,wrong}){const refs=useRef([]),[now,setNow]=useState(Date.now());useEffect(()=>{if(!value.running)return;const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[value.running]);const score=FACTS.filter(([a,b],i)=>Number(value.answers?.[i])===a*b).length,elapsed=value.time||Math.floor((now-(value.start||now))/1000);const stop=()=>setValue({...value,running:false,time:elapsed,finished:true});let result='';if(value.finished&&value.vp!==undefined&&value.vt!==undefined){const vp=Number(value.vp),vt=Number(value.vt);result=score>vp?'Lara gewinnt 👑':score<vp?'Varsenia gewinnt 😈':elapsed<vt?'Lara gewinnt 👑':elapsed>vt?'Varsenia gewinnt 😈':'Unentschieden 🤝'};return <>{!value.start?<div className="boss-start"><Trophy/><h2>Bereit für 20 Blitzaufgaben?</h2><p>Erst zählen die richtigen Antworten. Bei Gleichstand gewinnt die schnellere Zeit.</p><button className="button primary" onClick={()=>setValue({start:Date.now(),running:true,answers:{}})}>Timer starten</button></div>:<><div className="timer"><b>{elapsed} Sek.</b><span>{score} / 20 richtig</span></div><div className="facts">{FACTS.map(([a,b],i)=><label key={i}>{a} × {b}<input ref={x=>refs.current[i]=x} disabled={!value.running} inputMode="numeric" value={value.answers?.[i]||''} onChange={e=>setValue({...value,answers:{...value.answers,[i]:e.target.value}})} onKeyDown={e=>{if(e.key==='Enter')refs.current[i+1]?.focus()}}/></label>)}</div>{value.running&&<button className="button primary check" onClick={stop}>Fertig</button>}{value.finished&&<div className="boss-result"><h3>Laras Ergebnis: {score}/20 in {elapsed} Sekunden</h3><h3>Varsenias Ergebnis</h3><NumberInputs labels={['Punkte','Zeit in Sekunden']} value={[value.vp,value.vt]} setValue={x=>setValue({...value,vp:x[0],vt:x[1]})}/>{result&&<><div className="winner">{result}</div><button className="button primary" onClick={()=>finish(['rechnen'],Math.max(1,Math.round(score/4)))}>Level abschließen</button></>}</div>}</>}</>}

createRoot(document.getElementById('root')).render(<App/>);
